name: katseyy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.0.0
  image_cropper: ^8.0.2
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.5+3
  carousel_slider: ^5.0.0
  audioplayers: ^5.2.1
  table_calendar: ^3.1.2
  shimmer: ^3.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/cat.json
    - assets/clouds.json
    - assets/box.json
    - assets/owl.json
    - assets/welc.json
    - assets/cartographer.png
    - assets/meow.jpg
    - assets/diareal.png
    - assets/logo.png
    - assets/decide.mp3
    - assets/success.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
